services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend
    ports:
      - 80:3000
    depends_on:
      - postgres
    volumes: ## locally
      - /Users/benjaminrosshirt/Documents/Lessons:/app/lessons
    # volumes: ## lightsail
    #   - /home/ubuntu/Lessons:/app/lessons

volumes:
  db:
    driver: local
  